declare const ALARM_COLOR: number
declare const AM_ARC: number
declare const AM_DIR: number
declare const AM_HID: number
declare const AM_RDO: number
declare const AM_SYS: number
declare const BARGRAPH_BGCOLOR: number
declare const BARGRAPH1_COLOR: number
declare const BARGRAPH2_COLOR: number
declare const BLACK: number
declare const BLINK: number
declare const BLUE: number
declare const BOLD: number
declare const BOOL: number
declare const BRIGHTGREEN: number
declare const CENTER: number
declare const CHAR_CHANNEL: number
declare const CHAR_CYC: number
declare const CHAR_DELTA: number
declare const CHAR_DOWN: number
declare const CHAR_FUNCTION: number
declare const CHAR_INPUT: number
declare const CHAR_LEFT: number
declare const CHAR_LUA: number
declare const CHAR_POT: number
declare const CHAR_RIGHT: number
declare const CHAR_SLIDER: number
declare const CHAR_STICK: number
declare const CHAR_SWITCH: number
declare const CHAR_TELEMETRY: number
declare const CHAR_TRAINER: number
declare const CHAR_TRIM: number
declare const CHAR_UP: number
declare const COLOR_THEME_ACTIVE: number
declare const COLOR_THEME_DISABLED: number
declare const COLOR_THEME_EDIT: number
declare const COLOR_THEME_FOCUS: number
declare const COLOR_THEME_PRIMARY1: number
declare const COLOR_THEME_PRIMARY2: number
declare const COLOR_THEME_PRIMARY3: number
declare const COLOR_THEME_SECONDARY1: number
declare const COLOR_THEME_SECONDARY2: number
declare const COLOR_THEME_SECONDARY3: number
declare const COLOR_THEME_WARNING: number
declare const COLOR: number
declare const CURVE_AXIS_COLOR: number
declare const CURVE_COLOR: number
declare const CURVE_CURSOR_COLOR: number
declare const CUSTOM_COLOR: number
declare const DARKBLUE: number
declare const DARKBROWN: number
declare const DARKGREEN: number
declare const DARKGREY: number
declare const DARKRED: number
declare const DBLSIZE: number
declare const DOTTED: number
declare const ERASE: number
declare const EVT_MENU_BREAK: number
declare const EVT_PAGE_BREAK: number
declare const EVT_PAGE_LONG: number
declare const EVT_ENTER_BREAK: number
declare const EVT_ENTER_LONG: number
declare const EVT_EXIT_BREAK: number
declare const EVT_PLUS_BREAK: number
declare const EVT_MINUS_BREAK: number
declare const EVT_PLUS_FIRST: number
declare const EVT_MINUS_FIRST: number
declare const EVT_PLUS_REPT: number
declare const EVT_MINUS_REPT: number
declare const EVT_SYS_BREAK: number
declare const EVT_MODEL_FIRST: number
declare const EVT_TELEM_FIRST: number
declare const EVT_ROT_BREAK: number
declare const EVT_ROT_LONG: number
declare const EVT_ROT_LEFT: number
declare const EVT_ROT_RIGHT: number
declare const EVT_RTN_FIRST: number
declare const EVT_TOUCH_BREAK: number
declare const EVT_TOUCH_FIRST: number
declare const EVT_TOUCH_SLIDE: number
declare const EVT_TOUCH_TAP: number
declare const EVT_VIRTUAL_DEC_REPT: number
declare const EVT_VIRTUAL_DEC: number
declare const EVT_VIRTUAL_ENTER_LONG: number
declare const EVT_VIRTUAL_ENTER: number
declare const EVT_VIRTUAL_EXIT: number
declare const EVT_VIRTUAL_INC_REPT: number
declare const EVT_VIRTUAL_INC: number
declare const EVT_VIRTUAL_MENU_LONG: number
declare const EVT_VIRTUAL_MENU: number
declare const EVT_VIRTUAL_NEXT_PAGE: number
declare const EVT_VIRTUAL_NEXT_REPT: number
declare const EVT_VIRTUAL_NEXT: number
declare const EVT_VIRTUAL_PREV_PAGE: number
declare const EVT_VIRTUAL_PREV_REPT: number
declare const EVT_VIRTUAL_PREV: number
declare const FILL_WHITE: number
declare const FIXEDWIDTH: number
declare const FORCE: number
declare const FULLSCALE: number
declare const FUNC_ADJUST_GVAR: number
declare const FUNC_BACKGND_MUSIC_PAUSE: number
declare const FUNC_BACKGND_MUSIC: number
declare const FUNC_BACKLIGHT: number
declare const FUNC_BIND: number
declare const FUNC_DISABLE_TOUCH: number
declare const FUNC_HAPTIC: number
declare const FUNC_INSTANT_TRIM: number
declare const FUNC_LOGS: number
declare const FUNC_OVERRIDE_CHANNEL: number
declare const FUNC_PLAY_SCRIPT: number
declare const FUNC_PLAY_SOUND: number
declare const FUNC_PLAY_TRACK: number
declare const FUNC_PLAY_VALUE: number
declare const FUNC_RACING_MODE: number
declare const FUNC_RANGECHECK: number
declare const FUNC_RESET: number
declare const FUNC_SCREENSHOT: number
declare const FUNC_SET_FAILSAFE: number
declare const FUNC_SET_TIMER: number
declare const FUNC_TRAINER: number
declare const FUNC_VARIO: number
declare const FUNC_VOLUME: number
declare const GREEN: number
declare const GREY_DEFAULT: number
declare const GREY: number
declare const HEADER_BGCOLOR: number
declare const HEADER_COLOR: number
declare const HEADER_CURRENT_BGCOLOR: number
declare const HEADER_ICON_BGCOLOR: number
declare const INVERS: number
declare const LCD_H: number
declare const LCD_W: number
declare const LEFT: number
declare const LIGHTBROWN: number
declare const LIGHTGREY: number
declare const LIGHTWHITE: number
declare const LINE_COLOR: number
declare const LS_FUNC_ADIFFEGREATER: number
declare const LS_FUNC_AND: number
declare const LS_FUNC_ANEG: number
declare const LS_FUNC_APOS: number
declare const LS_FUNC_DIFFEGREATER: number
declare const LS_FUNC_EDGE: number
declare const LS_FUNC_EQUAL: number
declare const LS_FUNC_GREATER: number
declare const LS_FUNC_LESS: number
declare const LS_FUNC_NONE: number
declare const LS_FUNC_OR: number
declare const LS_FUNC_RANGE: number
declare const LS_FUNC_STICKY: number
declare const LS_FUNC_TIMER: number
declare const LS_FUNC_VALMOSTEQUAL: number
declare const LS_FUNC_VEQUAL: number
declare const LS_FUNC_VNEG: number
declare const LS_FUNC_VPOS: number
declare const LS_FUNC_XOR: number
declare const MAINVIEW_GRAPHICS_COLOR: number
declare const MAINVIEW_PANES_COLOR: number
declare const MAX_SENSORS: number
declare const MENU_HEADER_HEIGHT: number
declare const MENU_TITLE_BGCOLOR: number
declare const MENU_TITLE_COLOR: number
declare const MENU_TITLE_DISABLE_COLOR: number
declare const MIDSIZE: number
declare const MIXSRC_Ail: number
declare const MIXSRC_CH1: number
declare const MIXSRC_Ele: number
declare const MIXSRC_FIRST_INPUT: number
declare const MIXSRC_MAX: number
declare const MIXSRC_Rud: number
declare const MIXSRC_SA: number
declare const MIXSRC_SB: number
declare const MIXSRC_SC: number
declare const MIXSRC_SD: number
declare const MIXSRC_SE: number
declare const MIXSRC_SF: number
declare const MIXSRC_SG: number
declare const MIXSRC_SH: number
declare const MIXSRC_Thr: number
declare const ORANGE: number
declare const OVERLAY_COLOR: number
declare const PLAY_BACKGROUND: number
declare const PLAY_NOW: number
declare const PREC1: number
declare const PREC2: number
declare const RED: number
declare const REPLACE: number
declare const RIGHT: number
declare const ROTENC_HIGHSPEED: number
declare const ROTENC_LOWSPEED: number
declare const ROTENC_MIDSPEED: number
declare const ROUND: number
declare const SCROLLBOX_COLOR: number
declare const SHADOWED: number
declare const SMLSIZE: number
declare const SOLID: number
declare const SOURCE: number
declare const STRING: number
declare const SWITCH_COUNT: number
declare const SWSRC_LAST: number
declare const TEXT_BGCOLOR: number
declare const TEXT_COLOR: number
declare const TEXT_DISABLE_COLOR: number
declare const TEXT_INVERTED_BGCOLOR: number
declare const TEXT_INVERTED_COLOR: number
declare const TIMEHOUR: number
declare const TINSIZE: number
declare const TITLE_BGCOLOR: number
declare const TRIM_BGCOLOR: number
declare const TRIM_SHADOW_COLOR: number
declare const UNIT_AMPS: number
declare const UNIT_BITFIELD: number
declare const UNIT_CELLS: number
declare const UNIT_CELSIUS: number
declare const UNIT_DATETIME: number
declare const UNIT_DB: number
declare const UNIT_DEGREE: number
declare const UNIT_FAHRENHEIT: number
declare const UNIT_FEET_PER_SECOND: number
declare const UNIT_FEET: number
declare const UNIT_FLOZ: number
declare const UNIT_G: number
declare const UNIT_GPS: number
declare const UNIT_HERTZ: number
declare const UNIT_HOURS: number
declare const UNIT_KM: number
declare const UNIT_KMH: number
declare const UNIT_KTS: number
declare const UNIT_MAH: number
declare const UNIT_METERS_PER_SECOND: number
declare const UNIT_METERS: number
declare const UNIT_MILLIAMPS: number
declare const UNIT_MILLILITERS_PER_MINUTE: number
declare const UNIT_MILLILITERS: number
declare const UNIT_MILLIWATTS: number
declare const UNIT_MINUTES: number
declare const UNIT_MPH: number
declare const UNIT_MS: number
declare const UNIT_PERCENT: number
declare const UNIT_RADIANS: number
declare const UNIT_RAW: number
declare const UNIT_RPMS: number
declare const UNIT_SECONDS: number
declare const UNIT_TEXT: number
declare const UNIT_US: number
declare const UNIT_VOLTS: number
declare const UNIT_WATTS: number
declare const VALUE: number
declare const VCENTER: number
declare const WARNING_COLOR: number
declare const WHITE: number
declare const XXLSIZE: number
declare const YELLOW: number




declare function accessTelemetryPush(): void
declare function chdir(): void
declare function crossfireTelemetryPop(): void
declare function crossfireTelemetryPush(): void
declare function defaultChannel(): void
declare function defaultStick(): void
declare function dir(): void
declare function flushAudio(): void
declare function fstat(): void
declare function getAvailableMemory(): void
declare function getDateTime(): void
declare function getFieldInfo(source: number | string): TFieldInfo
declare function getFlightMode(): void
declare function getGeneralSettings(): void
declare function getGlobalTimer(): void
declare function getLogicalSwitchValue(): void
declare function getRAS(): void
declare function getRotEncSpeed(): void
declare function getRSSI(): void
declare function getRtcTime(): void
declare function getShmVar(): void
declare function getSourceIndex(source: string): number
declare function getSourceName(): void
declare function getSwitchIndex(): void
declare function getSwitchName(): void
declare function getSwitchValue(): void
declare function getTime(): number
declare function getTxGPS(): void
declare function getUsage(): void
declare function getValue(source: number | string): number
declare function getVersion(): void
declare function ghostTelemetryPop(): void
declare function ghostTelemetryPush(): void
declare function killEvents(): void
declare function loadScript(): void
declare function multiBuffer(): void
declare function playDuration(): void
declare function playFile(): void
declare function playHaptic(): void
declare function playNumber(): void
declare function playTone(): void
declare function popupConfirmation(): void
declare function popupInput(): void
declare function popupWarning(): void
declare function resetGlobalTimer(): void
declare function serialRead(): void
declare function serialWrite(): void
declare function setSerialBaudrate(): void
declare function setShmVar(): void
declare function setStickySwitch(): void
declare function setTelemetryValue(): void
declare function sources(): void
declare function sportTelemetryPop(): void
declare function sportTelemetryPush(): void
declare function switches(): void


interface TFieldInfo {
  id: number,
  name: string
  desc: string
  unit: number | number[]
}
